import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';

// Generated by 'flutter gen-l10n' — run that command after 'flutter pub get'
// import 'package:flutter_gen/gen_l10n/app_localizations.dart';

import 'core/constants/app_constants.dart';
import 'core/theme/app_theme.dart';
import 'logic/providers/settings_provider.dart';
import 'ui/screens/home_screen.dart';

class MeetingSilencerApp extends StatelessWidget {
  const MeetingSilencerApp({super.key});

  @override
  Widget build(BuildContext context) {
    final settings = context.watch<SettingsProvider>();

    return MaterialApp(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.lightTheme,
      darkTheme: AppTheme.darkTheme,
      themeMode: ThemeMode.system,
      locale: settings.locale,
      supportedLocales: AppConstants.supportedLocales,
      localizationsDelegates: const [
        // AppLocalizations.delegate, // Uncomment after running flutter gen-l10n
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
        GlobalCupertinoLocalizations.delegate,
      ],
      home: const HomeScreen(),
    );
  }
}
